// Busca de emoji em português. Os dados do emoji-mart só têm palavras em
// inglês; aqui ficam os termos que a gente digita no dia a dia (sem acento:
// a busca ignora acentos). Inglês continua valendo, pelos dados originais.
const EMOJI_KEYWORDS_PT = [
  ["rir risada risos kkk haha engracado", "😂 🤣 😆 😹 😄"],
  ["feliz alegre alegria sorriso sorrir", "😀 😃 😄 😁 😊 🙂 ☺️"],
  ["amor apaixonado paixao amo te amo", "😍 🥰 😘 ❤️ 💕 💖 💘 😻"],
  ["coracao", "❤️ 🧡 💛 💚 💙 💜 🖤 🤍 🤎 💔 ❣️ 💕 💞 💓 💗 💖 💘 💝"],
  ["beijo beijos", "😘 😗 😙 😚 💋"],
  ["triste tristeza", "😢 😭 😞 😔 🙁 ☹️ 😿 🥺"],
  ["chorar chorando choro lagrima", "😭 😢 😿"],
  ["raiva bravo irritado odio", "😠 😡 🤬 👿 💢"],
  ["medo assustado susto", "😨 😱 😰 😧"],
  ["surpreso surpresa espanto chocado", "😮 😯 😲 🤯 😳"],
  ["vergonha envergonhado timido", "😳 🙈 😊"],
  ["pensando pensar hmm", "🤔 🧐"],
  ["sono dormir cansado", "😴 🥱 😪 💤 🛌"],
  ["doente enjoado mal", "🤒 🤢 🤮 😷 🤧 🥴"],
  ["legal descolado oculos", "😎 🤓"],
  ["piscar piscada", "😉 😜"],
  ["lingua zoeira brincadeira doido", "😜 😝 😛 🤪"],
  ["silencio calado segredo", "🤫 🤐 😶"],
  ["abraco abracar", "🤗"],
  ["ok joia joinha positivo curti like sim", "👍 👌 🆗 ✅"],
  ["negativo nao deslike", "👎 🙅 ❌"],
  ["palmas aplauso aplausos parabens", "👏 🎉 🥳 🎊"],
  ["festa comemorar comemoracao", "🎉 🥳 🎊 🎈 🍾"],
  ["aniversario bolo", "🎂 🍰 🎁 🎈 🥳"],
  ["presente", "🎁"],
  ["obrigado obrigada gratidao agradecer por favor rezar orar amem", "🙏"],
  ["forca forte musculo academia", "💪 🏋️"],
  ["tchau oi ola acenar", "👋"],
  ["mao maos", "✋ 🤚 👐 🙌 🤲 👋 ✌️ 🤞 🤝"],
  ["paz", "✌️ ☮️ 🕊️"],
  ["dedos cruzados sorte torcendo", "🤞 🍀"],
  ["aperto acordo negocio fechado", "🤝"],
  ["apontar aqui", "👉 👈 👆 👇 ☝️"],
  ["olhos olhando olhar", "👀 👁️"],
  ["fogo quente top", "🔥"],
  ["estrela brilho brilhante", "⭐ 🌟 ✨ 💫"],
  ["cem perfeito", "💯"],
  ["certo check feito concluido pronto", "✅ ✔️ ☑️"],
  ["errado erro", "❌ ✖️ 🚫"],
  ["atencao alerta aviso cuidado urgente", "⚠️ ❗ ‼️ 🚨"],
  ["pergunta interrogacao duvida", "❓ ❔ 🤔"],
  ["dinheiro grana pagamento pix pagar", "💰 💵 💸 🤑 💳"],
  ["cartao", "💳"],
  ["telefone celular ligar ligacao zap whatsapp", "📱 📞 ☎️ 📲"],
  ["email carta mensagem", "📧 ✉️ 📩 💬"],
  ["relogio hora tempo atraso esperando espera", "⏰ ⌚ 🕐 ⏳ ⌛"],
  ["calendario data agenda", "📅 📆 🗓️"],
  ["casa lar", "🏠 🏡"],
  ["trabalho escritorio empresa", "💼 🏢 💻"],
  ["computador notebook", "💻 🖥️ ⌨️"],
  ["carro", "🚗 🚙 🏎️"],
  ["moto", "🏍️ 🛵"],
  ["aviao viagem ferias", "✈️ 🧳 🌍 🏖️"],
  ["onibus", "🚌"],
  ["entrega caminhao pacote caixa", "🚚 📦"],
  ["comida fome", "🍔 🍕 🍟 🌭 🍝 🍱 😋"],
  ["pizza", "🍕"],
  ["hamburguer lanche", "🍔"],
  ["cafe", "☕"],
  ["cerveja chopp bebida", "🍺 🍻 🍷 🥂 🍹"],
  ["vinho", "🍷"],
  ["agua", "💧"],
  ["fruta frutas", "🍎 🍌 🍓 🍇 🍉 🍍 🥭"],
  ["sol calor verao", "☀️ 🌞 🥵"],
  ["chuva", "🌧️ ☔ ⛈️"],
  ["frio inverno neve", "❄️ 🥶 ⛄"],
  ["lua noite", "🌙 🌛 🌜 🌚"],
  ["arco iris", "🌈"],
  ["flor flores", "🌸 🌹 🌺 🌻 🌷 💐"],
  ["planta arvore natureza", "🌱 🌳 🌴 🍀 🌿"],
  ["cachorro dog", "🐶 🐕"],
  ["gato", "🐱 🐈 😺"],
  ["macaco", "🐵 🙈 🙉 🙊"],
  ["passaro", "🐦 🕊️"],
  ["futebol bola gol", "⚽ 🥅"],
  ["musica", "🎵 🎶 🎧 🎤"],
  ["foto camera", "📷 📸"],
  ["video filme", "🎥 🎬 📹"],
  ["livro estudar estudo escola", "📚 📖 ✏️ 🎓"],
  ["ideia lampada", "💡"],
  ["foguete lancamento", "🚀"],
  ["trofeu campeao vitoria premio", "🏆 🥇 🏅"],
  ["alvo meta objetivo", "🎯"],
  ["grafico crescimento vendas", "📈 📊 📉"],
  ["cadeado seguranca senha chave", "🔒 🔐 🔑"],
  ["localizacao endereco mapa", "📍 🗺️ 📌"],
  ["loja compras carrinho", "🛒 🛍️ 🏪"],
  ["remedio saude hospital medico", "💊 🏥 😷"],
  ["bebe crianca", "👶 🧒"],
  ["homem", "👨 🧔"],
  ["mulher", "👩"],
  ["caveira morto morri", "💀 ☠️"],
  ["fantasma", "👻"],
  ["palhaco", "🤡"],
  ["anjo", "😇"],
  ["diabo", "😈"],
  ["coco", "💩"],
  ["brasil", "🇧🇷"],
  ["bandeira", "🏳️ 🏴 🏁 🚩"],
  ["natal", "🎄 🎅"],
  ["dinossauro", "🦖 🦕"],
  ["unicornio", "🦄"],
  ["enviar mandar", "📤 📨"]
].map(([words, emojis]) => [words.split(" "), emojis.split(" ")]);

export default EMOJI_KEYWORDS_PT;
